### ISSUE TITLE
Game view still doesn't recognize me as owner

### ISSUE THREAD

**Issue by zars15** [CrescentCode/ValkyrieServer#5]
I still don't see the owner options. The official site hasn't been updated yet? How often is the server updated, on every new commit on master?

**Comment by Gskartwii** [comment]
The official server is up-to-date. There shouldn't be any owner-specific options IIRC, but I may be wrong.

**Comment by Gskartwii** [comment]
Fixed by https://github.com/CrescentCode/ValkyrieServer/commit/ab734d702b673245146c548fe83abb9f08853c93
